name: pylinter
on:
  push:
    paths: "**/.py"
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: clone the code
        uses: actions/checkout@v4
      - name: install linter
        run: pip isntall ruff
      - name: checking ruff
        run: ruff check .
        
      
        
     
       
